# Generated by Django 5.0.2 on 2026-02-16 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event'), ('academic', 'Academic'), ('public', 'Public'), ('tender', 'Tender'), ('emergency', 'Emergency'), ('meeting', 'Meeting'), ('scheme', 'Scheme'), ('circular', 'Circular')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('teachers', 'Teachers'), ('citizens', 'Citizens'), ('staff', 'Staff')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='notices/documents/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
