# Generated by Django 5.0.2 on 2026-02-15 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('income', 'Income Certificate'), ('residence', 'Residence Certificate'), ('caste', 'Caste Certificate'), ('birth', 'Birth Certificate'), ('death', 'Death Certificate')], max_length=50)),
                ('applicant_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
