# Generated by Django 5.0.2 on 2026-02-16 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('near_limit', 'Near Limit'), ('over_budget', 'Over Budget')], default='on_track', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetrecord',
            name='department',
            field=models.CharField(choices=[('roads', 'Roads & Infrastructure'), ('water', 'Water Supply'), ('education', 'Education'), ('health', 'Health'), ('administration', 'Administration'), ('sanitation', 'Sanitation'), ('agriculture', 'Agriculture'), ('welfare', 'Social Welfare')], max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetrecord',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('materials', 'Materials'), ('labor', 'Labor'), ('equipment', 'Equipment'), ('services', 'Services'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='budget/receipts/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.budgetrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expense Entries',
                'ordering': ['-date'],
            },
        ),
    ]
